### ISSUE TITLE
Adding a daemon which can reason about the state in a DefaultCallback

### ISSUE THREAD

**Issue by kurtlawrence** [fschutt/azul#124]
Related to #59, is there the ability to add a daemon that knows a widget's state rather than the generic `T` (ie `MyAppData`). So far it seems the daemon functions of `AppStateNoData` will require the `DaemonCallbackType<T>` type which will only give `&mut T` in the function signature.

My current solution is to constrain `T: SomeTrait` where `SomeTrait` defines a function to obtain the data (`fn get(&mut self) -> &mut DataState`). This falls down if you want to include more than one of the widgets...

**Comment by fschutt** [comment]
This issue has been solved. The `TimerCallback` (`Daemon` was renamed to `Timer`) now accepts a `RefAny` struct which can contain any timer-specific data you want. See https://azul.rs/api/nightly#st.TimerCallbackType - the documentation is still lacking, but the second argument is a mutable reference to timer-local data.
