### ISSUE TITLE
Line break in text inputs size and draw incorrectly

### ISSUE THREAD

**Issue by JoshuaBehrens** [fschutt/azul#140]
## Description
Line break rendered as box and line height calculated incorrectly. Latter one noticed while writing this issue. I can make them separate issues.

## Version / OS
* azul version: 987177d761c87fa79cefeec953b1105c0ef13989
* Operating system: Linux 4.18.0-16-generic #17~18.04.1-Ubuntu SMP x86_64 GNU/Linux
* Windowing system: X11

## Steps to Reproduce
I used one of the textbox examples:
```rust
extern crate azul;

use azul::prelude::*;
use azul::widgets::text_input::*;

struct TestCrudApp {
    text_input: TextInputState,
}

impl Default for TestCrudApp {
    fn default() -> Self {
        Self {
            text_input: TextInputState::new("Hover mouse over rectangle and press keys")
        }
    }
}

impl Layout for TestCrudApp {
    fn layout(&self, info: LayoutInfo<Self>) -> Dom<Self> {
        TextInput::new()
            .bind(info.window, &self.text_input, &self)
            .dom(&self.text_input)
            .with_id("text_input_1")
    }
}

fn main() {
    let mut app = App::new(TestCrudApp::default(), AppConfig::default()).unwrap();
    let window = app.create_window(WindowCreateOptions::default(), css::native()).unwrap();
    app.run(window).unwrap();
}
```

## Additional Information
Without line break
![grafik](https://user-images.githubusercontent.com/1133593/55688522-c99dfd00-5979-11e9-9fe7-e1a52739e6e9.png)
With enough line breaks so the size calculation fits the drawing area for text (not the border?)
![grafik](https://user-images.githubusercontent.com/1133593/55688541-f3efba80-5979-11e9-8c71-d7a3f8756eab.png)

**Comment by fschutt** [comment]
Yeah, this has definitely been fixed by now, the TextInput works normal now. It may still accept "\n" character input (it shouldn't), but the line height does not get calculated wrong as it used to be the case.

**Comment by JoshuaBehrens** [comment]
Woohoo :) I didn't use it since then but thanks for the reminder. I'll probably look into this again
