### ISSUE TITLE
Text Shaping Example Issues

### ISSUE THREAD

**Issue by ForLoveOfCats** [fschutt/azul#146]
## Description

The text_shaping example has very strange layout and text render issues. The initial render seems ok but on any sort of redraw trigger it falls apart. Further, even when the layout is decent many unicode characters are rendered incorrectly however that is probably just an issue with whatever font Azul is falling back to.

## Version / OS

* azul version: `master` https://github.com/maps4print/azul/commit/8d3ce24d91d75588379c67b9a0176919f22799f7

* Operating system: Manjaro Linux

* Windowing system (X11 or Wayland, Linux only): `xorg 1.20.4-1`

## Steps to Reproduce

Clone Azul repo
Run `cargo run --example text_shaping`

## Additional Information

Initial layout and appearance
![image](https://user-images.githubusercontent.com/30666851/55748082-c05d7080-5a0b-11e9-9f60-5d3605bc51cd.png)

Layout after resizing or mouseover
![image](https://user-images.githubusercontent.com/30666851/55748115-d2d7aa00-5a0b-11e9-8a8a-f5d566031045.png)

**Comment by fschutt** [comment]
The initial layout is wrong, the second screen is what you should actually see. This doesn't happen in release mode, I think, it only happens with hot-reloading, so I'm putting this as a low priority bug.
