### ISSUE TITLE
hello world gui didn't start on win10

### ISSUE THREAD

**Issue by coolit** [fschutt/azul#196]
## Version / OS
win10

* azul version:
azul = { git = "https://github.com/maps4print/azul" }

## Steps to Reproduce
cargo run

## Additional Information
console started, but gui window failed
(exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)

**Comment by fschutt** [comment]
Could you add the **commit hash** of azul? Otherwise, I have no idea what version you pulled. Try the `unvendor_dependencies` branch otherwise.

**Comment by fschutt** [comment]
I remember that I ran into this bug and fixed it. Should be fixed on the master branch. Reopen if this issue still exists.
