### ISSUE TITLE
glium has triggered an OpenGL error during initialization.

### ISSUE THREAD

**Issue by jhessin** [fschutt/azul#201]
## Description

I just tried running the "Hello World" example from the Wiki and it compiles fine, but I get this error at runtime:
```
glium has triggered an OpenGL error during initialization. Please report this error: https://github.com/tomaka/glium/issues
glium has triggered an OpenGL error during initialization. Please report this error: https://github.com/tomaka/glium/issues
[ERROR][azul::logging] An unexpected panic ocurred, the program has to exit.
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: src/libcore/result.rs at line 997 in thread main

Error information:
called `Result::unwrap()` on an `Err` value: Shader compile error: Failed to compile vertex shader: E0: 0:2(10): error: GLSL 1.40 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES


Backtrace:

azul::logging::set_up_panic_hooks::panic_fn @ logging.rs:86
core::ops::function::Fn::call @ function.rs:69
 @ panicking.rs:478
 @ panicking.rs:381
 @ panicking.rs:85
core::result::unwrap_failed @ macros.rs:18
core::result::Result<T,E>::unwrap @ result.rs:798
azul::app::compile_screen_shader::{{closure}} @ app.rs:1389
core::option::Option<T>::get_or_insert_with @ option.rs:814
azul::app::compile_screen_shader @ app.rs:1388
azul::app::draw_texture_to_screen @ app.rs:1399
azul::app::render_inner @ app.rs:1334
azul::app::App<T>::run_inner @ app.rs:456
azul::app::App<T>::run @ app.rs:283
main::main @ main.rs:22
std::rt::lang_start::{{closure}} @ rt.rs:64
 @ rt.rs:49
 @ panicking.rs:293
 @ lib.rs:87
 @ panicking.rs:272
 @ panic.rs:388
 @ rt.rs:48
std::rt::lang_start @ rt.rs:64
unresolved function

sh: 1: Syntax error: Bad function name
[ERROR][azul::window] Shutdown error: Context error
```
It seems like this is primarily an issue with my openGL library, but I'm not sure how to get the right one.

## Version / OS

* azul version:
azul = { git = "https://github.com/maps4print/azul" }

* Operating system:
debian 10 "Buster
linux-version (4.9.0-9-amd64)

* Windowing system (X11 or Wayland, Linux only):
X11 (I think - what's Wayland?)

## Steps to Reproduce

I was working through the wiki to get an understanding of the package. This error occurs after running this code:
```rust
extern crate azul;

use azul::prelude::*;

struct MyDataModel { }

impl Layout for MyDataModel {
    fn layout(&self, _: LayoutInfo<Self>) -> Dom<Self> {
        Dom::div()
    }
}

fn main() {
    let mut app = App::new(MyDataModel { }, AppConfig::default()).unwrap();
    let window = app.create_window(WindowCreateOptions::default(), css::native()).unwrap();
    app.run(window).unwrap();
}
```
I did have some kind of issue earlier in the process while running this:
```bash
sudo apt install \
    cmake libxcb-xkb-dev libfontconfig1-dev libgles2-mesa-dev \
    libfreetype6-dev libexpat-dev
```
I got this as a result:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libexpat1-dev' instead of 'libexpat-dev'
cmake is already the newest version (3.7.2-1).
libfontconfig1-dev is already the newest version (2.11.0-6.7+b1).
libfontconfig1-dev set to manually installed.
libfreetype6-dev is already the newest version (2.6.3-3.2).
libexpat1-dev is already the newest version (2.2.0-2+deb9u2).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgles2-mesa-dev : Depends: libegl1-mesa-dev but it is not going to be installed
 libxcb-xkb-dev : Depends: libxcb-xkb1 (= 1.12-1) but 1.13.1-2 is to be installed
E: Unable to correct problems, you have held broken packages.
```
I'm not sure what caused it but it may be related.

**Comment by jhessin** [comment]
Update: I was able to install the packages I couldn't install before using aptitude instead of apt, but I still get the same message when trying to run the hello-world example.

**Comment by fschutt** [comment]
What driver do you have? What is the output of `glxinfo` and `glxinfo | grep OpenGl`?

**Comment by jhessin** [comment]
what package has glxinfo? I don't seem to have that program.

**Comment by jhessin** [comment]
glxinfo | grep OpenGL

```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ironlake Mobile 
OpenGL version string: 2.1 Mesa 18.3.6
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 18.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
```

**Comment by fschutt** [comment]
Yeah, you're on OpenGL ES 2.0 and OpenGL 2.1 - you need at least OpenGL 3.0 or OpenGL ES 3.0. Your drivers are too old - while azul could do a fallback to a built-in software OpenGL renderer, this is currently not done (it's too much work atm). You could try:

1. Updating your graphics drivers 
2. start cargo with `LIBGL_ALWAYS_SOFTWARE=1 cargo run` to let the application run using a the systems software renderer (in your case Mesa)
3. There is an implementation of OSMesa + Rust bindings somewhere, but atm I can't find it. Instead of initializing the OpenGL context from the system (in `FakeDisplay::new()`), the context is initialized via an in-memory framebuffer. However you'd have to write the bindings for software rendering yourself.

The screen shader is pretty simple, I've lowered the requirement to `#version 100`, which should make it run again - however, webrender won't run, since WR requires `#version 140` at least.

**Comment by fschutt** [comment]
glium is no longer used (I use a custom GL-function-pointer loader) and the screen shader isn't used either anymore (replaced by raw framebuffer swap). I think this issue can be closed.
