### ISSUE TITLE
Labels are not displayed.

### ISSUE THREAD

**Issue by VengeQ** [fschutt/azul#235]
Am I did something wrong or is it a bug?
## Description
* Texts in labels are not displayed.
* Labels of button  are not displayed.
## Version / OS
* azul version:
Latest from branch="unvendor_dependencies"
https://github.com/maps4print/azul/commit/dcc69cd12acc77676ce2228064395228d17eac93

* Operating system:
Windows 10 version 1607 (OS Build 14393.3326)

* Windowing system (X11 or Wayland, Linux only):
N/A

* Rust version
rustc 1.41.0-nightly (ded5ee001 2019-11-13)
cargo 1.40.0-nightly (5da4b4d47 2019-10-28)

## Steps to Reproduce
Just cargo run.
My main.rs(Very similar to "hello_world" from examples):
```rust
extern crate azul;
use azul::prelude::*;
use azul::widgets::{button::Button, label::Label, };
const CSS: &str = "
#label1 {
    width: 40px;
    height: 40px;
    background-color:red;
    font-color:blue;
}
#button1 {
     top:40px;
     width: 40px;
     height: 40px;
}
";
struct DataModel {
    counter: usize
}
impl Layout for DataModel {
    fn layout(&self, _: LayoutInfo) -> Dom<Self> {
        let label = Label::new(format!("counter: {}", self.counter))
            .dom()
            .with_id("label1");
        let button = Button::with_label("Update counter")
            .dom()
            .with_id("button1")
            .with_callback(On::MouseUp, update_counter);
        Dom::new(NodeType::Div).with_child(label).with_child(button)
       // Dom::div().with_child(label).with_child(button)
    }
}
fn update_counter(event: CallbackInfo<DataModel>) -> UpdateScreen {
    event.state.counter += 1;
    println!("counter: {}",event.state.counter ); // counter works properly
    Redraw
}
fn main() {
    let app = App::new(DataModel { counter: 0 }, AppConfig::default()).unwrap();
    let window = WindowCreateOptions::new(css::override_native(CSS).unwrap());
    app.run(window);
}
```

## Additional Information
When use css::override_native in window:
![image](https://user-images.githubusercontent.com/25214270/71565875-951d3300-2afe-11ea-83f4-a6df06d09b81.png)

When use css::native:
![image](https://user-images.githubusercontent.com/25214270/71565883-a0705e80-2afe-11ea-9003-5401bed41005.png)

**Comment by fschutt** [comment]
Yeah, no, this is a known bug in the layout solver. The font instance keys aren't always generated. Will be fixed, but I haven't had the time recently.

**Comment by fschutt** [comment]
This has been fixed, the labels now display properly.
