### ISSUE TITLE
NNemec's fork?

### ISSUE THREAD

**Issue by liusong1111** [fschutt/azul#244]
I noticed recent change of README, and then know the state of this project.
We should keep patient.

I also found a fork:
https://github.com/NNemec/azul/tree/fix-hello-world
> This branch is 201 commits ahead, 101 commits behind maps4print:master.

I tried NNemec's examples, they partially works.

and, the original maps4print's unvendor_dependencies_2 branch says:
> This branch is 167 commits ahead, 101 commits behind master.

I am wondering whether you known each other's work.

Again, Thanks to you all.
This project is promising, especially comparing to electron.

**Comment by fschutt** [comment]
I didn't know about the fork. Looks good so far, especially that he fixed the block layout (?). Doing the layout solver is the hardest task.

Again, I didn't say it's abandoned, it's just going very very slowly.

**Comment by fschutt** [comment]
Well, the alpha is released now, I don't think his fork will be necessary anymore.
