### ISSUE TITLE
Installation build fails. error[E0107]: wrong number of type arguments: expected 1, found 0

### ISSUE THREAD

**Issue by trayanr** [fschutt/azul#247]
## Description

When following the installation instructions, build fails, with following errors:
```
error[E0107]: wrong number of type arguments: expected 1, found 0
   --> /home/trayan/.cargo/git/checkouts/azul-f3b1e21a5e685cad/7ed9603/cargo/azul/../../azul/wr_translate.rs:123:73
    |
123 |     pub(crate) fn translate_logical_position(input: LogicalPosition) -> WinitLogicalPosition {
    |                                                                         ^^^^^^^^^^^^^^^^^^^^ expected 1 type argument

error[E0107]: wrong number of type arguments: expected 1, found 0
   --> /home/trayan/.cargo/git/checkouts/azul-f3b1e21a5e685cad/7ed9603/cargo/azul/../../azul/wr_translate.rs:128:65
    |
128 |     pub(crate) fn translate_logical_size(input: LogicalSize) -> WinitLogicalSize {
    |                                                                 ^^^^^^^^^^^^^^^^ expected 1 type argument

error[E0107]: wrong number of type arguments: expected 1, found 0
   --> /home/trayan/.cargo/git/checkouts/azul-f3b1e21a5e685cad/7ed9603/cargo/azul/../../azul/wr_translate.rs:133:65
    |
133 |     pub(crate) const fn translate_winit_logical_position(input: WinitLogicalPosition) -> LogicalPosition {
    |                                                                 ^^^^^^^^^^^^^^^^^^^^ expected 1 type argument

error[E0107]: wrong number of type arguments: expected 1, found 0
   --> /home/trayan/.cargo/git/checkouts/azul-f3b1e21a5e685cad/7ed9603/cargo/azul/../../azul/wr_translate.rs:138:61
    |
138 |     pub(crate) const fn translate_winit_logical_size(input: WinitLogicalSize) -> LogicalSize {
    |                                                             ^^^^^^^^^^^^^^^^ expected 1 type argument

error[E0107]: wrong number of type arguments: expected 1, found 0
   --> /home/trayan/.cargo/git/checkouts/azul-f3b1e21a5e685cad/7ed9603/cargo/azul/../../azul/wr_translate.rs:163:75
    |
163 |     pub(crate) fn translate_physical_position(input: PhysicalPosition) -> WinitPhysicalPosition {
    |                                                                           ^^^^^^^^^^^^^^^^^^^^^ expected 1 type argument

error[E0107]: wrong number of type arguments: expected 1, found 0
   --> /home/trayan/.cargo/git/checkouts/azul-f3b1e21a5e685cad/7ed9603/cargo/azul/../../azul/wr_translate.rs:167:67
    |
167 |     pub(crate) fn translate_physical_size(input: PhysicalSize) -> WinitPhysicalSize {
    |                                                                   ^^^^^^^^^^^^^^^^^ expected 1 type argument
```

## Version / OS

* azul version:
As per the instructions my deps look like this:
```
[dependencies]
azul = { git = "https://github.com/maps4print/azul", rev = "7ed96030ac9d2233877f00611867208373ae25ff" }
```

* Operating system:
Ubuntu 18.04.4 LTS 

* Windowing system (X11 or Wayland, Linux only):
X11

## Steps to Reproduce

```
sudo apt install \
    cmake libxcb-xkb-dev libfontconfig1-dev libgles2-mesa-dev \
    libfreetype6-dev libexpat-dev

cargo new --bin my_first_azul_app
cd my_first_azul_app
cargo run
```

## Additional Information

rustc -vV returns:
```
rustc 1.42.0 (b8cedc004 2020-03-09)
binary: rustc
commit-hash: b8cedc00407a4c56a3bda1ed605c6fc166655447
commit-date: 2020-03-09
host: x86_64-unknown-linux-gnu
release: 1.42.0
LLVM version: 9.0
```

**Comment by sokyrko** [comment]
Same for me.

**Comment by sokyrko** [comment]
Seems like the issue occurs because of changed "glutin" library API.
`cargo/azul/Cargo.toml` requires "0.22.0-alpha3" which is ok, but I see `Compiling glutin v0.22.1` in a `cargo build` log.

**Comment by trayanr** [comment]
My cargo also builds glutin v0.22.1. So I wanted to test things out locally, and downloaded azul to my machine. Wired the toml to the local copy of the crate and started experimenting with versions. For some reason when I specify that I want to use glutin 0.*.0 it upgrades it to the latest (eg. 0.21.0 -> 0.21.2; 0.22.0 -> 0.22.1). For some reason `cargo build` does not take to account the last subversion and downloads the latest. That's my guess.

**Comment by magnusart** [comment]
I get the same on MacOS X.

**Comment by ChrisWhealy** [comment]
I get the same build error on MacOS, but before all of the above `wrong number of type arguments` errors occur, first I get a whole set of errors that come from the dependency on `glutin`

Maybe Azul's [current dependency](https://github.com/maps4print/azul/blob/master/cargo/azul/Cargo.toml) on glutin version `0.22.0-alpha3` is the problem because glutin is now up to [`0.24.0`](https://crates.io/crates/glutin)? (Just a guess though)

```
error[E0428]: the name `wr_translate_font_instance_platform_options` is defined multiple times
   --> /Users/chris/.cargo/git/checkouts/azul-f3b1e21a5e685cad/7ed9603/cargo/azul/../../azul/wr_translate.rs:655:1
    |
646 | fn wr_translate_font_instance_platform_options(fio: FontInstancePlatformOptions) -> WrFontInstancePlatformOptions {
    | ----------------------------------------------------------------------------------------------------------------- previous definition of the value `wr_translate_font_instance_platform_options` here
...
655 | const fn wr_translate_font_instance_platform_options(fio: FontInstancePlatformOptions) -> WrFontInstancePlatformOptions {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `wr_translate_font_instance_platform_options` redefined here
    |
    = note: `wr_translate_font_instance_platform_options` must be defined only once in the value namespace of this module

error[E0432]: unresolved import `glutin::platform::windows`
   --> /Users/chris/.cargo/git/checkouts/azul-f3b1e21a5e685cad/7ed9603/cargo/azul/../../azul/window.rs:580:27
    |
580 |     use glutin::platform::windows::WindowBuilderExtMac;
    |                           ^^^^^^^ could not find `windows` in `platform`

error[E0432]: unresolved import `glutin::platform::macos::WindowExtMacOs`
   --> /Users/chris/.cargo/git/checkouts/azul-f3b1e21a5e685cad/7ed9603/cargo/azul/../../azul/window.rs:860:9
    |
860 |     use glutin::platform::macos::WindowExtMacOs;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^--------------
    |         |                        |
    |         |                        help: a similar name exists in the module (notice the capitalization): `WindowExtMacOS`
    |         no `WindowExtMacOs` in `platform::macos`

error[E0432]: unresolved import `glutin::platform::macos::WindowExtMacOs`
   --> /Users/chris/.cargo/git/checkouts/azul-f3b1e21a5e685cad/7ed9603/cargo/azul/../../azul/window.rs:904:9
    |
904 |     use glutin::platform::macos::WindowExtMacOs;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^--------------
    |         |                        |
    |         |                        help: a similar name exists in the module (notice the capitalization): `WindowExtMacOS`
    |         no `WindowExtMacOs` in `platform::macos`

error[E0432]: unresolved import `crate::glutin::platform::unix`
    --> /Users/chris/.cargo/git/checkouts/azul-f3b1e21a5e685cad/7ed9603/cargo/azul/../../azul/window.rs:1007:34
     |
1007 |     use crate::glutin::platform::unix::EventLoopWindowTargetExtUnix;
     |                                  ^^^^ could not find `unix` in `platform`

error[E0432]: unresolved imports `webrender::api::FontLCDFilter`, `webrender::api::FontHinting`
  --> /Users/chris/.cargo/git/checkouts/azul-f3b1e21a5e685cad/7ed9603/cargo/azul/../../azul/wr_translate.rs:53:5
   |
53 |     FontLCDFilter as WrFontLCDFilter,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `FontLCDFilter` in `api`
54 |     FontHinting as WrFontHinting,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `FontHinting` in `api`
```

**Comment by xemwebe** [comment]
> My cargo also builds glutin v0.22.1. So I wanted to test things out locally, and downloaded azul to my machine. Wired the toml to the local copy of the crate and started experimenting with versions. For some reason when I specify that I want to use glutin 0.*.0 it upgrades it to the latest (eg. 0.21.0 -> 0.21.2; 0.22.0 -> 0.22.1). For some reason `cargo build` does not take to account the last subversion and downloads the latest. That's my guess.

To enforce sticking to the exact version, you would need put a "=" in front of the version number, e.g. `version = "=0.22.0-alpha3"` . 

Though on my machine, this causes only wrong number of type errors elsewhere.

**Comment by t0mj3dus0r** [comment]
> > My cargo also builds glutin v0.22.1. So I wanted to test things out locally, and downloaded azul to my machine. Wired the toml to the local copy of the crate and started experimenting with versions. For some reason when I specify that I want to use glutin 0.*.0 it upgrades it to the latest (eg. 0.21.0 -> 0.21.2; 0.22.0 -> 0.22.1). For some reason `cargo build` does not take to account the last subversion and downloads the latest. That's my guess.
> 
> To enforce sticking to the exact version, you would need put a "=" in front of the version number, e.g. `version = "=0.22.0-alpha3"` .
> 
> Though on my machine, this causes only wrong number of type errors elsewhere.

Tried to compile Azul manually with your tip, cargo took the good glutin version but it still fails :(

**Comment by andreypronin** [comment]
The current workaround is to explicitly specify both winit and glutin versions in your Cargo.toml. Just look what's in Crago.lock in the appropriate branch.

E.g. currently for master:
glutin = { version = "=0.22.0-alpha3" } 
winit = { version = "=0.20.0-alpha3" }
azul = { git = "https://github.com/maps4print/azul" }

For unvendor_dependencies_2:
glutin = { version = "=0.22.0-alpha5" } 
winit = { version = "=0.20.0-alpha4" }
azul = { git = "https://github.com/maps4print/azul", branch = "unvendor_dependencies_2" }

**Comment by koyo-nic** [comment]
```sh
cargo install cargo-edit
# echo  'azul = "0.1.0"' > Cargo.toml
# add 'azul = "0.1.0"' to Cargo.toml
Cargo add azul
```
[Stackoverflow ref:](https://stackoverflow.com/questions/37706999/error-installing-a-crate-via-cargo-specified-package-has-no-binaries)
``` Cargo run``` worked as expected, but still stuck in the next section of first GUI
see image below
![cargo-add-azul](https://user-images.githubusercontent.com/50481279/84573524-aeaef000-ada9-11ea-9899-8872d22c8df2.png)

**Comment by koyo-nic** [comment]
> ```shell
> cargo install cargo-edit
> # echo  'azul = "0.1.0"' > Cargo.toml
> # add 'azul = "0.1.0"' to Cargo.toml
> Cargo add azul
> ```
> 
> [Stackoverflow ref:](https://stackoverflow.com/questions/37706999/error-installing-a-crate-via-cargo-specified-package-has-no-binaries)
> ` Cargo run` worked as expected, but still stuck in the next section of first GUI
> see image below
> ![cargo-add-azual](https://user-images.githubusercontent.com/50481279/84573741-29c4d600-adab-11ea-99dc-65cc216e9ddb.png)

the above sure does install azul but doesn't include some of azul's modules like App thus i  reverted back to @andreypronin  workaround

**Comment by fschutt** [comment]
Both glutin and winit have been updated, this issue should be fixed on master. Please reopen if the issue still exists.
