### ISSUE TITLE
License not updated on official website

### ISSUE THREAD

**Issue by Kibouo** [fschutt/azul#268]
https://azul.rs/index.html still reports the license to be MIT, not LGPLv3.
 
![image](https://user-images.githubusercontent.com/25766329/116636925-cca22680-a962-11eb-8ba4-f5c2cdec620f.png)

**Comment by fschutt** [comment]
Fixed. 

![image](https://user-images.githubusercontent.com/12084016/116769459-92a55300-aa3c-11eb-85fb-cc907eb10663.png)
