### ISSUE TITLE
`flex-grow: 0` still distributing remaining space, intended behavior?

### ISSUE THREAD

**Issue by code-mc** [fschutt/azul#41]
I was wondering if the current flexbox behavior is intended. When you use flexbox on the web, not setting any flex-grow values basically means "distribute the children inside the flexbox without altering their size". You can then use child items that contain text which will nicely show one after the other inside the flexbox, without any extra space between each item or any added "padding" to the text items.

When I'm using azul this doesn't seem to be possible, by default flexbox items are stretched to fill all remaining space. The only way to get around this issue is by explicitly specifying the width or height of the item, but this isn't feasible when you want to use this to "auto size" a text element according to its content.

Here are a few different flex-grow combinations:

#### Azul
![](https://i.imgur.com/qL7xMcv.png)
#### Web
![](https://i.imgur.com/b34EwNu.png)

#### Azul
![](https://i.imgur.com/qL7xMcv.png)
#### Web
![](https://i.imgur.com/8pUk1fp.png)

#### Azul
![](https://i.imgur.com/m7KwZBJ.png)
#### Web
![](https://i.imgur.com/J4KAFeB.png)

#### Azul
![](https://i.imgur.com/m7KwZBJ.png)
#### Web
![](https://i.imgur.com/v1zG9Vf.png)

#### Azul
![](https://i.imgur.com/NlivEch.png)
#### Web
![](https://i.imgur.com/2ozPqQm.png)

#### Azul
![](https://i.imgur.com/NlivEch.png)
#### Web
![](https://i.imgur.com/UVvquhE.png)

Web reference can be found here: https://jsfiddle.net/Lwm8k5t9/3/

**Comment by fschutt** [comment]
I know, this is a very annoying bug that I've also run into. It should later be fixed with properly implementing `flex-start` and `flex-end`. Azul does have the information on how large the children have to be, it just doesn't use it yet.

**Comment by fschutt** [comment]
Oh yeah, right now, everything below flex-grow: 1 is ignored. flex-grow: 0 is the same as flex-grow: 1 (to avoid divide-by-0 mistakes for now)

**Comment by fschutt** [comment]
This bug has been fixed (in https://github.com/fschutt/azul/commit/19a4276c2f7b6e66270c01285b22401e6709fa14). `flex-grow: 0` is now the default (as in a web browser) and you have to explicitly set `flex-grow: 1` on the node that you'd like to stretch.

Note that there might still be bugs with text breaking / text layout in general, but this specific bug has been fixed. You can now construct the tab layout as you'd expect.
